### PR TITLE
Batch tables during schema sync

### LINKED ISSUE #581: Bug/Accident: Surrealist freeze with 10s of thousands of databases 😄
### Describe the bug

I accidentally created more databases than I wanted, but in turn, run into an interesting issue where the Surrealist strait freezes up, and even after waiting a few minutes, it remains unusable. In my case, I had made about 50k schemaless tables, and I can see that the application tries to fetch the schema for all tables one by one, thus dealing with a lot of work that blocks user interaction.

### Steps to reproduce

- Make 1000+ tables, ideally 10k+
- Open the database with Surrealist
- Try to click around the navigation
- Try to execute a query

### Expected behaviour

While 50k tables are not intended, a few thousand tables should not cause UI application issues, as the application can only display one table at a time anyway.

### Surrealist Environment

Version: 3.1.1
Flags: feature_flags: false, query_view: true, explorer_view: true, graphql_view: true, designer_view: true, auth_view: true, functions_view: true, models_view: true, apidocs_view: true, cloud_view: true, themes: true, syntax_themes: false, newsfeed: true, database_version_check: true, highlight_tool: false, legacy_serve: false, cloud_endpoints: production, cloud_access: false, cloud_killswitch: true, changelog: auto

### Contact Details

adam@liszkai.dev

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by macjuul**
partially resolves #581

### CODE REVIEW

File: src/util/schema.tsx [hunk 1]
```diff
@@ -109,7 +111,7 @@ export async function syncConnectionSchema(options?: SchemaSyncOptions) {
 		for (const [idx, tableName] of tablesToSync.entries()) {
 			adapter.log("Schema", `Updating table ${tableName}`);
 
-			const tableStruct = tbInfoMap[idx];
+			const tableStruct = tbInfoMap[idx].result as SchemaInfoTB;
```
Comment (adaliszk) [inline src/util/schema.tsx:114]: Hmm, while it is not my code base, wouldn't it be possible to add a generic to the executeQuery, which then can be passed to the under-the-hood `query_raw`? That way, casting would not be necessary.
